// exports
export const APP_LIST_REQUEST = 'APP_LIST_REQUEST';
export const APP_LIST_SUCCESS = 'APP_LIST_SUCCESS';
export const APP_LIST_FAILURE = 'APP_LIST_FAILURE';

export const APP_CREATE_REQUEST = 'APP_CREATE_REQUEST';
export const APP_CREATE_SUCCESS_EFFECT = 'APP_CREATE_SUCCESS_EFFECT';
export const APP_CREATE_SUCCESS = 'APP_CREATE_SUCCESS';
export const APP_CREATE_FAILURE_EFFECT = 'APP_CREATE_FAILURE_EFFECT';
export const APP_CREATE_FAILURE = 'APP_CREATE_FAILURE';

export const APP_LOAD_CONFIG_REQUEST = 'APP_LOAD_CONFIG_REQUEST';
export const APP_LOAD_CONFIG_SUCCESS = 'APP_LOAD_CONFIG_SUCCESS';
export const APP_LOAD_CONFIG_FAILURE = 'APP_LOAD_CONFIG_FAILURE';

export const APP_UPDATE_CONFIG_REQUEST = 'APP_UPDATE_CONFIG_REQUEST';
export const APP_UPDATE_CONFIG_SUCCESS_EFFECT = 'APP_UPDATE_CONFIG_SUCCESS_EFFECT';
export const APP_UPDATE_CONFIG_SUCCESS = 'APP_UPDATE_CONFIG_SUCCESS';
export const APP_UPDATE_CONFIG_FAILURE_EFFECT = 'APP_UPDATE_CONFIG_FAILURE_EFFECT';
export const APP_UPDATE_CONFIG_FAILURE = 'APP_UPDATE_CONFIG_FAILURE';

export const APP_FETCH_PREFERENCES_REQUEST = 'APP_FETCH_PREFERENCES_REQUEST';
export const APP_FETCH_PREFERENCES_SUCCESS = 'APP_FETCH_PREFERENCES_SUCCESS';
export const APP_FETCH_PREFERENCES_FAILURE = 'APP_FETCH_PREFERENCES_FAILURE';

export const APP_UPDATE_PREFERENCES_REQUEST = 'APP_UPDATE_PREFERENCES_REQUEST';
export const APP_UPDATE_PREFERENCES_SUCCESS = 'APP_UPDATE_PREFERENCES_SUCCESS';
export const APP_UPDATE_PREFERENCES_FAILURE = 'APP_UPDATE_PREFERENCES_FAILURE';