// exports - Authentication
export const AUTHENTICATION_INIT_REQUEST = 'AUTHENTICATION_INIT_REQUEST';
export const AUTHENTICATION_INIT_SUCCESS = 'AUTHENTICATION_INIT_SUCCESS';
export const AUTHENTICATION_INIT_FAILURE = 'AUTHENTICATION_INIT_FAILURE';

// exports - Logout
export const AUTHENTICATION_LOGOUT_REQUEST = 'AUTHENTICATION_LOGOUT_REQUEST';
export const AUTHENTICATION_LOGOUT_SUCCESS = 'AUTHENTICATION_LOGOUT_SUCCESS';
export const AUTHENTICATION_LOGOUT_FAILURE = 'AUTHENTICATION_LOGOUT_FAILURE';