// exports
export const BILLING_USAGE_REQUEST = 'BILLING_USAGE_REQUEST';
export const BILLING_USAGE_SUCCESS = 'BILLING_USAGE_SUCCESS';
export const BILLING_USAGE_FAILURE = 'BILLING_USAGE_FAILURE';

export const BILLING_PLANS_REQUEST = 'BILLING_PLANS_REQUEST';
export const BILLING_PLANS_SUCCESS = 'BILLING_PLANS_SUCCESS';
export const BILLING_PLANS_FAILURE = 'BILLING_PLANS_FAILURE';