// exports
export const CHAT_CLEAR_RESULTS = 'CHAT_CLEAR_RESULTS';

export const CHAT_FETCH_HISTORY_REQUEST = 'CHAT_FETCH_HISTORY_REQUEST';
export const CHAT_FETCH_HISTORY_SUCCESS = 'CHAT_FETCH_HISTORY_SUCCESS';
export const CHAT_FETCH_HISTORY_FAILURE = 'CHAT_FETCH_HISTORY_FAILURE';

export const CHAT_JOIN_REQUEST = 'CHAT_JOIN_REQUEST';
export const CHAT_JOIN_SUCCESS_EFFECT = 'CHAT_JOIN_SUCCESS_EFFECT';
export const CHAT_JOIN_SUCCESS = 'CHAT_JOIN_SUCCESS';
export const CHAT_JOIN_FAILURE_EFFECT = 'CHAT_JOIN_FAILURE_EFFECT';
export const CHAT_JOIN_FAILURE = 'CHAT_JOIN_FAILURE';

export const CHAT_SEND_MESSAGE_REQUEST = 'CHAT_SEND_MESSAGE_REQUEST';
export const CHAT_SEND_MESSAGE_SUCCESS_EFFECT = 'CHAT_SEND_MESSAGE_SUCCESS_EFFECT';
export const CHAT_SEND_MESSAGE_SUCCESS = 'CHAT_SEND_MESSAGE_SUCCESS';
export const CHAT_SEND_MESSAGE_FAILURE_EFFECT = 'CHAT_SEND_MESSAGE_FAILURE_EFFECT';
export const CHAT_SEND_MESSAGE_FAILURE = 'CHAT_SEND_MESSAGE_FAILURE';

export const CHAT_MESSAGE_DELETE_REQUEST = 'CHAT_MESSAGE_DELETE_REQUEST';
export const CHAT_MESSAGE_DELETE_SUCCESS_EFFECT = 'CHAT_MESSAGE_DELETE_SUCCESS_EFFECT';
export const CHAT_MESSAGE_DELETE_SUCCESS = 'CHAT_MESSAGE_DELETE_SUCCESS';
export const CHAT_MESSAGE_DELETE_FAILURE_EFFECT = 'CHAT_MESSAGE_DELETE_FAILURE_EFFECT';
export const CHAT_MESSAGE_DELETE_FAILURE = 'CHAT_MESSAGE_DELETE_FAILURE';

export const CHAT_FETCH_ADMIN_LOGS_HISTORY_REQUEST = 'CHAT_FETCH_ADMIN_LOGS_HISTORY_REQUEST';
export const CHAT_FETCH_ADMIN_LOGS_HISTORY_SUCCESS = 'CHAT_FETCH_ADMIN_LOGS_HISTORY_SUCCESS';
export const CHAT_FETCH_ADMIN_LOGS_HISTORY_FAILURE = 'CHAT_FETCH_ADMIN_LOGS_HISTORY_FAILURE';