// exports
export const DEBUG_CLEAR_RESULTS = 'DEBUG_CLEAR_RESULTS';

export const DEBUG_FETCH_LOGS_REQUEST = 'DEBUG_FETCH_LOGS_REQUEST';
export const DEBUG_FETCH_LOGS_SUCCESS = 'DEBUG_FETCH_LOGS_SUCCESS';
export const DEBUG_FETCH_LOGS_FAILURE = 'DEBUG_FETCH_LOGS_FAILURE';