// exports
export const MODERATION_FETCH_STATUS_REQUEST = 'MODERATION_FETCH_STATUS_REQUEST';
export const MODERATION_FETCH_STATUS_SUCCESS = 'MODERATION_FETCH_STATUS_SUCCESS';
export const MODERATION_FETCH_STATUS_FAILURE = 'MODERATION_FETCH_STATUS_FAILURE';

export const MODERATION_UPDATE_STATUS_REQUEST = 'MODERATION_UPDATE_STATUS_REQUEST';
export const MODERATION_UPDATE_STATUS_SUCCESS_EFFECT = 'MODERATION_UPDATE_STATUS_SUCCESS_EFFECT';
export const MODERATION_UPDATE_STATUS_SUCCESS = 'MODERATION_UPDATE_STATUS_SUCCESS';
export const MODERATION_UPDATE_STATUS_FAILURE = 'MODERATION_UPDATE_STATUS_FAILURE';
export const MODERATION_UPDATE_STATUS_FAILURE_EFFECT = 'MODERATION_UPDATE_STATUS_FAILURE_EFFECT';