// exports - List
export const NOTIFICATIONS_LIST_REQUEST = 'NOTIFICATIONS_LIST_REQUEST';
export const NOTIFICATIONS_LIST_SUCCESS = 'NOTIFICATIONS_LIST_SUCCESS';
export const NOTIFICATIONS_LIST_FAILURE = 'NOTIFICATIONS_LIST_FAILURE';

// exports - Create
export const NOTIFICATIONS_CREATE_REQUEST = 'NOTIFICATIONS_CREATE_REQUEST';
export const NOTIFICATIONS_CREATE_SUCCESS_EFFECT = 'NOTIFICATIONS_CREATE_SUCCESS_EFFECT';
export const NOTIFICATIONS_CREATE_SUCCESS = 'NOTIFICATIONS_CREATE_SUCCESS';
export const NOTIFICATIONS_CREATE_FAILURE_EFFECT = 'NOTIFICATIONS_CREATE_FAILURE_EFFECT';
export const NOTIFICATIONS_CREATE_FAILURE = 'NOTIFICATIONS_CREATE_FAILURE';

// exports - Update
export const NOTIFICATIONS_UPDATE_REQUEST = 'NOTIFICATIONS_UPDATE_REQUEST';
export const NOTIFICATIONS_UPDATE_SUCCESS_EFFECT = 'NOTIFICATIONS_UPDATE_SUCCESS_EFFECT';
export const NOTIFICATIONS_UPDATE_SUCCESS = 'NOTIFICATIONS_UPDATE_SUCCESS';
export const NOTIFICATIONS_UPDATE_FAILURE_EFFECT = 'NOTIFICATIONS_UPDATE_FAILURE_EFFECT';
export const NOTIFICATIONS_UPDATE_FAILURE = 'NOTIFICATIONS_UPDATE_FAILURE';

// exports - Delete
export const NOTIFICATIONS_DELETE_REQUEST = 'NOTIFICATIONS_DELETE_REQUEST';
export const NOTIFICATIONS_DELETE_SUCCESS_EFFECT = 'NOTIFICATIONS_DELETE_SUCCESS_EFFECT';
export const NOTIFICATIONS_DELETE_SUCCESS = 'NOTIFICATIONS_DELETE_SUCCESS';
export const NOTIFICATIONS_DELETE_FAILURE_EFFECT = 'NOTIFICATIONS_DELETE_FAILURE_EFFECT';
export const NOTIFICATIONS_DELETE_FAILURE = 'NOTIFICATIONS_DELETE_FAILURE';