// exports - Clear
export const QUERIES_CLEAR_SEARCH_RESULT = 'QUERIES_CLEAR_SEARCH_RESULT';
export const QUERIES_CLEAR_TRENDING_WORDS_RESULT = 'QUERIES_CLEAR_TRENDING_WORDS_RESULT';

// exports - List - Messages
export const QUERIES_LIST_MESSAGES_REQUEST = 'QUERIES_LIST_MESSAGES_REQUEST';
export const QUERIES_LIST_MESSAGES_SUCCESS = 'QUERIES_LIST_MESSAGES_SUCCESS';
export const QUERIES_LIST_MESSAGES_FAILURE = 'QUERIES_LIST_MESSAGES_FAILURE';

// exports - List - Keywords
export const QUERIES_LIST_KEYWORDS_REQUEST = 'QUERIES_LIST_KEYWORDS_REQUEST';
export const QUERIES_LIST_KEYWORDS_SUCCESS = 'QUERIES_LIST_KEYWORDS_SUCCESS';
export const QUERIES_LIST_KEYWORDS_FAILURE = 'QUERIES_LIST_KEYWORDS_FAILURE';

// exports - Create / Update - Messages
export const QUERIES_CREATE_UPDATE_MESSAGES_REQUEST = 'QUERIES_CREATE_UPDATE_MESSAGES_REQUEST';
export const QUERIES_CREATE_UPDATE_MESSAGES_SUCCESS_EFFECT = 'QUERIES_CREATE_UPDATE_MESSAGES_SUCCESS_EFFECT';
export const QUERIES_CREATE_UPDATE_MESSAGES_SUCCESS = 'QUERIES_CREATE_UPDATE_MESSAGES_SUCCESS';
export const QUERIES_CREATE_UPDATE_MESSAGES_FAILURE_EFFECT = 'QUERIES_CREATE_UPDATE_MESSAGES_FAILURE_EFFECT';
export const QUERIES_CREATE_UPDATE_MESSAGES_FAILURE = 'QUERIES_CREATE_UPDATE_MESSAGES_FAILURE';

// exports - Create - Keywords
export const QUERIES_CREATE_KEYWORDS_REQUEST = 'QUERIES_CREATE_KEYWORDS_REQUEST';
export const QUERIES_CREATE_KEYWORDS_SUCCESS_EFFECT = 'QUERIES_CREATE_KEYWORDS_SUCCESS_EFFECT';
export const QUERIES_CREATE_KEYWORDS_SUCCESS = 'QUERIES_CREATE_KEYWORDS_SUCCESS';
export const QUERIES_CREATE_KEYWORDS_FAILURE_EFFECT = 'QUERIES_CREATE_KEYWORDS_FAILURE_EFFECT';
export const QUERIES_CREATE_KEYWORDS_FAILURE = 'QUERIES_CREATE_KEYWORDS_FAILURE';

// exports - Delete - Messages
export const QUERIES_DELETE_MESSAGES_REQUEST = 'QUERIES_DELETE_MESSAGES_REQUEST';
export const QUERIES_DELETE_MESSAGES_SUCCESS = 'QUERIES_DELETE_MESSAGES_SUCCESS';
export const QUERIES_DELETE_MESSAGES_FAILURE = 'QUERIES_DELETE_MESSAGES_FAILURE';

// exports - Delete - Keywords
export const QUERIES_DELETE_KEYWORDS_REQUEST = 'QUERIES_DELETE_KEYWORDS_REQUEST';
export const QUERIES_DELETE_KEYWORDS_SUCCESS = 'QUERIES_DELETE_KEYWORDS_SUCCESS';
export const QUERIES_DELETE_KEYWORDS_FAILURE = 'QUERIES_DELETE_KEYWORDS_FAILURE';

// exports - Export - Messages Query
export const QUERIES_EXPORT_MESSAGES_PAGE = 'QUERIES_EXPORT_MESSAGES_PAGE';

export const QUERIES_EXPORT_MESSAGES_REQUEST = 'QUERIES_EXPORT_MESSAGES_REQUEST';
export const QUERIES_EXPORT_MESSAGES_SUCCESS_EFFECT = 'QUERIES_EXPORT_MESSAGES_SUCCESS_EFFECT';
export const QUERIES_EXPORT_MESSAGES_SUCCESS = 'QUERIES_EXPORT_MESSAGES_SUCCESS';
export const QUERIES_EXPORT_MESSAGES_FAILURE_EFFECT = 'QUERIES_EXPORT_MESSAGES_FAILURE_EFFECT';
export const QUERIES_EXPORT_MESSAGES_FAILURE = 'QUERIES_EXPORT_MESSAGES_FAILURE';

// exports - Execute - Messages Query
export const QUERIES_EXECUTE_MESSAGES_REQUEST = 'QUERIES_EXECUTE_MESSAGES_REQUEST';
export const QUERIES_EXECUTE_MESSAGES_SUCCESS = 'QUERIES_EXECUTE_MESSAGES_SUCCESS';
export const QUERIES_EXECUTE_MESSAGES_FAILURE = 'QUERIES_EXECUTE_MESSAGES_FAILURE';

export const QUERIES_EXECUTE_MESSAGES_CONTEXT_REQUEST = 'QUERIES_EXECUTE_MESSAGES_CONTEXT_REQUEST';
export const QUERIES_EXECUTE_MESSAGES_CONTEXT_SUCCESS = 'QUERIES_EXECUTE_MESSAGES_CONTEXT_SUCCESS';
export const QUERIES_EXECUTE_MESSAGES_CONTEXT_FAILURE = 'QUERIES_EXECUTE_MESSAGES_CONTEXT_FAILURE';

// exports - Execute - Metrics Query
export const QUERIES_EXECUTE_METRICS_APP_LIST_REQUEST = 'QUERIES_EXECUTE_METRICS_APP_LIST_REQUEST';
export const QUERIES_EXECUTE_METRICS_APP_LIST_SUCCESS = 'QUERIES_EXECUTE_METRICS_APP_LIST_SUCCESS';
export const QUERIES_EXECUTE_METRICS_APP_LIST_FAILURE = 'QUERIES_EXECUTE_METRICS_APP_LIST_FAILURE';

export const QUERIES_EXECUTE_METRICS_TRENDS_CARDS_REQUEST = 'QUERIES_EXECUTE_METRICS_TRENDS_CARDS_REQUEST';
export const QUERIES_EXECUTE_METRICS_TRENDS_CARDS_SUCCESS = 'QUERIES_EXECUTE_METRICS_TRENDS_CARDS_SUCCESS';
export const QUERIES_EXECUTE_METRICS_TRENDS_CARDS_FAILURE = 'QUERIES_EXECUTE_METRICS_TRENDS_CARDS_FAILURE';

export const QUERIES_EXECUTE_METRICS_TRENDS_GRAPHS_REQUEST = 'QUERIES_EXECUTE_METRICS_TRENDS_GRAPHS_REQUEST';
export const QUERIES_EXECUTE_METRICS_TRENDS_GRAPHS_SUCCESS = 'QUERIES_EXECUTE_METRICS_TRENDS_GRAPHS_SUCCESS';
export const QUERIES_EXECUTE_METRICS_TRENDS_GRAPHS_FAILURE = 'QUERIES_EXECUTE_METRICS_TRENDS_GRAPHS_FAILURE';

// exports - Execute - Keywords Query
export const QUERIES_EXECUTE_KEYWORDS_TRENDING_WORDS_REQUEST = 'QUERIES_EXECUTE_KEYWORDS_TRENDING_WORDS_REQUEST';
export const QUERIES_EXECUTE_KEYWORDS_TRENDING_WORDS_SUCCESS = 'QUERIES_EXECUTE_KEYWORDS_TRENDING_WORDS_SUCCESS';
export const QUERIES_EXECUTE_KEYWORDS_TRENDING_WORDS_FAILURE = 'QUERIES_EXECUTE_KEYWORDS_TRENDING_WORDS_FAILURE';