// exports
export const REPORT_CLEAR_RESULTS = 'REPORT_CLEAR_RESULTS';

export const REPORT_MESSAGE_REQUEST = 'REPORT_MESSAGE_REQUEST';
export const REPORT_MESSAGE_SUCCESS_EFFECT = 'REPORT_MESSAGE_SUCCESS_EFFECT';
export const REPORT_MESSAGE_SUCCESS = 'REPORT_MESSAGE_SUCCESS';
export const REPORT_MESSAGE_FAILURE_EFFECT = 'REPORT_MESSAGE_FAILURE_EFFECT';
export const REPORT_MESSAGE_FAILURE = 'REPORT_MESSAGE_FAILURE';

export const REPORT_FETCH_USERS_REQUEST = 'REPORT_FETCH_USERS_REQUEST';
export const REPORT_FETCH_USERS_SUCCESS = 'REPORT_FETCH_USERS_SUCCESS';
export const REPORT_FETCH_USERS_FAILURE = 'REPORT_FETCH_USERS_FAILURE';

export const REPORT_FETCH_MESSAGES_REQUEST = 'REPORT_FETCH_MESSAGES_REQUEST';
export const REPORT_FETCH_MESSAGES_SUCCESS = 'REPORT_FETCH_MESSAGES_SUCCESS';
export const REPORT_FETCH_MESSAGES_FAILURE = 'REPORT_FETCH_MESSAGES_FAILURE';